FROM ubuntu:bionic

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        libcurl4-openssl-dev \
        libboost-python-dev \
        libgtk2.0-dev

# Install Python packages
COPY requirements-amd64.txt ./requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install -r requirements.txt
RUN pip3 install ptvsd==4.1.3

# Cleanup
RUN rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove

COPY ./app .

# Expose the port
EXPOSE 8080

CMD [ "sh", "-c", "python3 -u ./main.py" ]